Sort directors
iliyasold/movies pull request #2
Opened 2017-10-03 13:32 UTC by iliyasold

2017-10-10 21:46 UTC, zverok requested changes

2017-10-10 21:46 UTC, zverok commented on les.rb
> +File.foreach(file) do |line|
Чтобы наполнить коллекцию фильмов, лучше использовать `map`

2017-10-10 21:46 UTC, zverok commented on les.rb
> +    puts "#{a[1]} #{"*" * b} #{}" if a[1].include?('Max')
Да выкинь эту часть, путается тут только.

2017-10-10 21:46 UTC, zverok commented on les.rb
> +  }
Если вынести названия ключей в константу, тут можно использовать `zip` и собирать хеш одним маленьким выражением.

2017-10-10 21:46 UTC, zverok commented on les.rb
> +    countries << movieslib[:country]
Зачем?

2017-10-10 21:46 UTC, zverok commented on les.rb
> +    puts "#{movie[:title]} - #{movie[:timing]}"
Задание (3) рекомендует сделать метод для вывода фильмов.

2017-10-10 21:46 UTC, zverok commented on les.rb
> +	  movies.each { |director| array << director[:director].split.reverse.join(' ') }
`map`. и хорошо бы режиссёров отсортировать по фамилиям, но при этом оставить их ФИО неизменными (не менять местами имя и фамилию)

2017-10-10 21:46 UTC, zverok commented on les.rb
> +    end
Зачем так сложно?..

2017-10-10 21:46 UTC, zverok commented on les.rb
> +  	print_block { (countries.delete_if {|country| country == "USA" }).size }
Метод `count` умеет много полезного, достаточно его :)

2017-10-11 07:38 UTC, iliyasold commented on les.rb
> +    puts "#{a[1]} #{"*" * b} #{}" if a[1].include?('Max')
Ok

2017-10-12 09:19 UTC, iliyasold commented on les.rb
> +File.foreach(file) do |line|
Ok

2017-10-12 20:04 UTC, iliyasold commented on les.rb
> +  }
Ok

2017-10-12 20:39 UTC, iliyasold commented on les.rb
> +    countries << movieslib[:country]
ok

2017-10-12 21:02 UTC, iliyasold commented on les.rb
> +    end
Ok

2017-10-12 21:02 UTC, iliyasold commented on les.rb
> +  	print_block { (countries.delete_if {|country| country == "USA" }).size }
Ok

2017-10-12 21:53 UTC, iliyasold commented on les.rb
> +	  movies.each { |director| array << director[:director].split.reverse.join(' ') }
Ok

2017-10-13 07:07 UTC, zverok commented on les.rb
> +puts movies.map { |director| director[:director] }.uniq.map { |director| director.split(" ") }.sort_by{ |family| family.last }.map { |director| director.join(' ') }
Если тут делать `split` прямо внутри `sort_by`, то `join` не понадобится.

2017-10-13 07:07 UTC, zverok commented on les.rb
> +  puts "#{movie[:title]} - #{movie[:date]} - #{movie[:genre]}"
А задание (3)? 

> Для этого стоит написать свой метод, который выводит массив фильмов.

2017-10-13 07:56 UTC, iliyasold commented on les.rb
> +  puts "#{movie[:title]} - #{movie[:date]} - #{movie[:genre]}"
Ok

2017-10-13 09:06 UTC, iliyasold commented on les.rb
> +puts movies.map { |director| director[:director] }.uniq.map { |director| director.split(" ") }.sort_by{ |family| family.last }.map { |director| director.join(' ') }
Ok

2017-10-13 09:06 UTC, merged