Third task
iliyasold/movies pull request #4
Opened 2017-10-20 10:55 UTC by iliyasold

2017-10-23 14:18 UTC, zverok requested changes

2017-10-23 14:18 UTC, zverok commented on les.rb
> +while num <= 9 do
В Ruby почти никогда не нужны стандартные циклы (for, while и т.п.), если тебе вдруг понадобился — что-то пошло не так :) `each` тут должно было хватить, в принципе... Но на самом деле всё решение надо пересматривать.

2017-10-23 14:18 UTC, zverok commented on les.rb
> +while num <= 12 do
Опять же, если бы не надо было пересматривать всё решение, то хотя бы эти два while надо было объединить в один цикл, видно же что они одно и то же делают.

2017-10-23 14:18 UTC, zverok commented on les.rb
> +end
...но! Получается что чтобы посчитать эту простую задачу, у тебя происходит 12 проходов по массиву (каждый `count` перебирает все элементы, проверяя подходят ли они под текущий месяц).

Ну представь что тебе надо было бы пересчитать реальные объекты (скажем, диски с теми же фильмами — стопку из 250 штук). Сначала прошёл по всей стопке, и посчитал сколько фильмов вышло в январе... Потом начала сначала, ещё раз перебрал все и посчитал сколько вышло в феврале... И так далее. Вряд ли бы ты стал так делать в жизни, правда?..

2017-10-23 14:18 UTC, zverok commented on les.rb
> +while num <= 12 do
Этот while тоже стыдный, всё переделать :)

2017-10-24 02:50 UTC, iliyasold commented on les.rb
> +while num <= 12 do
ok

2017-10-24 18:45 UTC, zverok requested changes

2017-10-24 18:45 UTC, zverok commented on les.rb
> +puts movies.map { |director| director.director }.uniq.sort_by { |family| family.split(" ").last }
а) почему переменная в блоке называется `director`, кстати? тебе не кажется, что `director.director` даже выглядит дико?
б) такие случаи (один метод, без аргументов) можно упрощать с помощью `Symbol.to_proc`

2017-10-24 18:45 UTC, zverok commented on les.rb
> +puts "#{movies.count {|movie| movie.country.include?("USA") == false }} films are not made in the USA"
Ой. Это я в прошлом задании это вот `== false` пропустил?.. Зря! Сравнение с `true` и `false` нужно крайне редко, почти никогда. просто `!movie.country.include?('USA')`

2017-10-24 18:45 UTC, zverok commented on les.rb
> +puts mounths.sort.uniq.map { |elem| "#{mounths.count(elem)} снято в #{mounths_name[elem]} " }
Так опять же 12 раз `count` проходится по всему массиву? Надо в 1 проход всё посчитать.

2017-10-24 18:45 UTC, zverok commented on les.rb
> +mounths = movies.map { |movie| Date._strptime(movie[:date]) }.delete_if { |x| x == nil }.map { |item| item[:mon] }
Кстати, `delete_if { |x| x == nil }` → `compact`.

2017-10-26 12:14 UTC, merged